<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KempDec.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>KempDec.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Xmutarn.Core\Xmutarn.Core.csproj" />
    <ProjectReference Include="..\..\src\Xmutarn\Xmutarn.csproj" />
  </ItemGroup>

</Project>
