//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmutarn.Web.Resources.Pages.Docs {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IntroductionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntroductionResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xmutarn.Web.Resources.Pages.Docs.IntroductionResource", typeof(IntroductionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Xmutarn combina o poder do C# com a flexibilidade do CSS. Este guia rápido mostra como instalar e referenciar os arquivos..
        /// </summary>
        internal static string IntroDescription {
            get {
                return ResourceManager.GetString("IntroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Introdução.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Após a instalação, os arquivos ficam em node_modules/xmutarn/dist. Copie os arquivos necessários para a pasta pública do seu projeto, por exemplo lib/xmutarn, e referencie-os:.
        /// </summary>
        internal static string NpmAfterInstall {
            get {
                return ResourceManager.GetString("NpmAfterInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instale o pacote:.
        /// </summary>
        internal static string NpmInstallText {
            get {
                return ResourceManager.GetString("NpmInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ver no NPM.
        /// </summary>
        internal static string NpmSeeOnNpm {
            get {
                return ResourceManager.GetString("NpmSeeOnNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via NPM.
        /// </summary>
        internal static string NpmTitle {
            get {
                return ResourceManager.GetString("NpmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicione o pacote ao projeto:.
        /// </summary>
        internal static string NugetInstallText {
            get {
                return ResourceManager.GetString("NugetInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ver no NuGet.
        /// </summary>
        internal static string NugetSeeOnNuget {
            get {
                return ResourceManager.GetString("NugetSeeOnNuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via NuGet (Blazor).
        /// </summary>
        internal static string NugetTitle {
            get {
                return ResourceManager.GetString("NugetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Introdução.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Com o CSS e o JS referenciados, você pode começar a usar os utilitários e componentes do Xmutarn imediatamente..
        /// </summary>
        internal static string ReadyDescription {
            get {
                return ResourceManager.GetString("ReadyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pronto para usar.
        /// </summary>
        internal static string ReadyTitle {
            get {
                return ResourceManager.GetString("ReadyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No arquivo host/entrada do seu aplicativo (o HTML onde você inclui recursos globais), adicione:.
        /// </summary>
        internal static string RefDescription {
            get {
                return ResourceManager.GetString("RefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referenciando os arquivos.
        /// </summary>
        internal static string RefTitle {
            get {
                return ResourceManager.GetString("RefTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via NPM.
        /// </summary>
        internal static string SidebarNpm {
            get {
                return ResourceManager.GetString("SidebarNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via NuGet (Blazor).
        /// </summary>
        internal static string SidebarNuget {
            get {
                return ResourceManager.GetString("SidebarNuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pronto para usar.
        /// </summary>
        internal static string SidebarReady {
            get {
                return ResourceManager.GetString("SidebarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referenciando os arquivos.
        /// </summary>
        internal static string SidebarRef {
            get {
                return ResourceManager.GetString("SidebarRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via Yarn.
        /// </summary>
        internal static string SidebarYarn {
            get {
                return ResourceManager.GetString("SidebarYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assim como no NPM, os arquivos ficam em node_modules/xmutarn/dist. Copie-os para a pasta pública do seu projeto (ex.: lib/xmutarn) e referencie-os:.
        /// </summary>
        internal static string YarnAfterInstall {
            get {
                return ResourceManager.GetString("YarnAfterInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instale o pacote:.
        /// </summary>
        internal static string YarnInstallText {
            get {
                return ResourceManager.GetString("YarnInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação via Yarn.
        /// </summary>
        internal static string YarnTitle {
            get {
                return ResourceManager.GetString("YarnTitle", resourceCulture);
            }
        }
    }
}
